// <auto-generated />
namespace TrashGuy.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changedblackoutdateasnullable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changedblackoutdateasnullable));
        
        string IMigrationMetadata.Id
        {
            get { return "201705042005100_changed blackout date as nullable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
