// <auto-generated />
namespace TrashGuy.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class blackoutandspecialpickuptableadd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(blackoutandspecialpickuptableadd));
        
        string IMigrationMetadata.Id
        {
            get { return "201705032142011_blackout and specialpickup table add"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
